/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "text-secondary": "#666666",
        "on-surface": "#1d1c11",
        "surface-tint": "#676000",
        "text-primary": "#1A1A1A",
        "surface-container": "#f3eedd",
        "surface-bright": "#fff9e8",
        "on-tertiary-container": "#007074",
        "on-background": "#1d1c11",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-fixed-dim": "#c8c6c5",
        "outline-variant": "#ccc7ad",
        "primary-fixed": "#f5e642",
        "surface-variant": "#e7e2d1",
        "on-primary-container": "#6e6600",
        "on-tertiary-fixed": "#002021",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1f1c00",
        "status-error": "#EF4444",
        "status-info": "#3B82F6",
        "banner-crit-bg": "#FFF0F0",
        "on-primary-fixed-variant": "#4e4800",
        "on-tertiary-fixed-variant": "#004f52",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "bg-page": "#FAFAF7",
        "accent-hover": "#E8D930",
        "outline": "#7b7861",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f4e2",
        "secondary-container": "#e2dfde",
        "text-disabled": "#AAAAAA",
        "tertiary-container": "#5bf8ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f6f1df",
        "on-secondary-container": "#636262",
        "border-primary": "#1A1A1A",
        "inverse-surface": "#323125",
        "primary": "#676000",
        "surface": "#fff9e8",
        "surface-container-high": "#ede8d7",
        "accent-dark-text": "#7A6F00",
        "tertiary": "#00696d",
        "secondary-fixed": "#e5e2e1",
        "inverse-primary": "#d8ca23",
        "surface-dim": "#dfdac9",
        "banner-warn-bg": "#FFF8E6",
        "on-secondary-fixed-variant": "#474746",
        "bg-card": "#FFFFFF",
        "tertiary-fixed-dim": "#2fdbe2",
        "primary-fixed-dim": "#d8ca23",
        "surface-container-highest": "#e7e2d1",
        "status-warning": "#F59E0B",
        "secondary": "#5f5e5e",
        "status-success": "#22C55E",
        "background": "#fff9e8",
        "on-error-container": "#93000a",
        "primary-container": "#f5e642",
        "tertiary-fixed": "#5bf8ff",
        "on-surface-variant": "#4a4734",
        "bg-surface-alt": "#F5F5F0"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "md": "16px",
        "xs": "4px",
        "2xl": "48px",
        "base": "4px",
        "lg": "24px",
        "3xl": "64px",
        "xl": "32px",
        "sm": "8px"
      },
      "fontFamily": {
        "page-title": ["Syne"],
        "micro-label": ["Space Grotesk"],
        "section-head": ["Syne"],
        "body-copy": ["Space Grotesk"],
        "metadata": ["JetBrains Mono"],
        "card-title": ["Space Grotesk"],
        "hero-display": ["Syne"],
        "label-caps": ["Space Grotesk"]
      },
      "fontSize": {
        "page-title": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.5px", "fontWeight": "700"}],
        "micro-label": ["9px", {"lineHeight": "1.0", "letterSpacing": "2px", "fontWeight": "600"}],
        "section-head": ["16px", {"lineHeight": "1.4", "letterSpacing": "-0.2px", "fontWeight": "700"}],
        "body-copy": ["13px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "metadata": ["11px", {"lineHeight": "1.0", "fontWeight": "400"}],
        "card-title": ["14px", {"lineHeight": "1.4", "letterSpacing": "-0.1px", "fontWeight": "600"}],
        "hero-display": ["36px", {"lineHeight": "1.1", "letterSpacing": "-1px", "fontWeight": "800"}],
        "label-caps": ["10px", {"lineHeight": "1.0", "letterSpacing": "1.5px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
